version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip --root-user-action=ignore
      - pip install -r requirements.txt --root-user-action=ignore

  build:
    commands:
      - echo "Running migrations..."

artifacts:
  files:
    - '**/*'
  discard-paths: no