version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running migrations..."
      - python manage.py migrate
      - echo "Collecting static files..."
      - python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
  discard-paths: no