# Generated by Django 5.1.6 on 2025-03-18 03:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="herosection",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="sportcategory",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="contactus",
            name="country",
            field=django_countries.fields.CountryField(default="AU", max_length=2),
            preserve_default=False,
        ),
    ]
