# Generated by Django 5.1.6 on 2025-03-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_faqcategory_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person (e.g., John Doe)", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role of the person (e.g., CEO of Company)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description or testimonial text"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image of the person", upload_to="testimonials/"
                    ),
                ),
                (
                    "star_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        help_text="Star rating (e.g., 5)",
                    ),
                ),
            ],
        ),
    ]
