# Generated by Django 5.1.6 on 2025-04-02 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_testimonial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["-id"]},
        ),
    ]
