# Generated by Django 5.1.6 on 2025-04-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BettingBasicConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "concept_type",
                    models.CharField(
                        choices=[
                            ("point_spreads", "Point Spreads"),
                            ("moneylines", "Moneylines"),
                            ("totals", "Totals (Over/Under)"),
                            ("prop_bets", "Prop Bets"),
                            ("parlays", "Parlays"),
                            ("teasers", "Teasers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("example", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class or similar",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Betting Basic Concept",
                "verbose_name_plural": "Betting Basic Concepts",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BettingInfoSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=300, null=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="betting_info/"),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("text_image", "Text with Image"),
                            ("image_text", "Image with Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Betting Info Section",
                "verbose_name_plural": "Betting Info Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BettingTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="betting_tips/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Betting Tip",
                "verbose_name_plural": "Betting Tips",
                "ordering": ["order"],
            },
        ),
    ]
